[package]
name = "avis_audio_lib"
version = "0.0.0"
edition = "2021"
description = "audio library for avis (stands for Audio VISualiser)"
license = "GPL-3.0-or-later"

[dependencies]
crossbeam-channel = "~0.5.4"
cpal = "~0.13.5"
log = "~0.4.16"
